# Generated by Django 3.1.4 on 2022-01-21 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='movieID',
            new_name='movie_id',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='movieID',
            new_name='movie_id',
        ),
    ]
